import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { CourseSidebar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="grid grid-cols-5">
                    <div className="col">
                        <CourseSidebar />
                    </div>
                    <div className="col-span-4 flex flex-col p-5 bg-slate-950">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
