import type { CourseCardProps as Course } from "../types";

export const COURSES: Course[] = [
  {
    title: "Zapier",
    description:
      "Learn everything you need to know about Zapier with this course",
    price: 99,
    slug: "zapier",
    image_url: "ZAPIER_COURSE.png",
    difficulty: "Begginer",
  },
  {
    title: "Make",
    description:
      "Learn everything you need to know about Make with this course",
    price: 99,
    slug: "make",
    image_url: "MAKE_COURSE.png",
    difficulty: "Begginer",
  },
  {
    title: "Slack APIs and Workflows",
    description:
      "Learn everything you need to know about Slack Workflows and Automations with this course",
    price: 99,
    image_url: "SLACK_AUTOMATIONS_COURSE.png",
    slug: "slack-automations-course",
    difficulty: "Intermediate",
  },
  {
    title: "Facebook Ads for Developers",
    description: "Learn everything you need to know about Ads with this course",
    price: 200,
    image_url: "META_DEVELOPERS_COURSE.png",
    slug: "facebook-ads-for-developers",
    difficulty: "Advanced",
  },
  {
    title: "HTTP and APIs",
    description: "Learn everything you need to know about Ads with this course",
    price: 99,
    slug: "facebook-ads-for-developers",
    difficulty: "Intermediate",
  },
  {
    title: "GHL OAuth 2.0",
    description: "Learn everything you need to know about Ads with this course",
    price: 10,
    slug: "facebook-ads-for-developers",
    difficulty: "Intermediate",
  },
  {
    title: "OAuth 2.0",
    description: "Learn everything you need to know about Ads with this course",
    price: 10,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "GHL Marketplace Apps Development",
    description: "Learn everything you need to know about Ads with this course",
    price: 200,
    slug: "facebook-ads-for-developers",
    difficulty: "Advanced",
  },
  {
    title: "Stripe and Ecommerce Integrations",
    description: "Learn everything you need to know about Ads with this course",
    price: 200,
    slug: "facebook-ads-for-developers",
    difficulty: "Intermediate",
  },
  {
    title: "JavaScript for Automations",
    description: "Learn everything you need to know about Ads with this course",
    price: 50,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "Python for Automations",
    description: "Learn everything you need to know about Ads with this course",
    price: 50,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "RoboCorp for Automations",
    description: "Learn everything you need to know about Ads with this course",
    price: 50,
    slug: "facebook-ads-for-developers",
    difficulty: "Intermediate",
  },
  {
    title: "AWS",
    description: "Learn everything you need to know about Ads with this course",
    price: 100,
    slug: "facebook-ads-for-developers",
    difficulty: "Intermediate",
  },
  {
    title: "Call Center GHL",
    description: "Learn everything you need to know about Ads with this course",
    price: 100,
    slug: "facebook-ads-for-developers",
    difficulty: "Intermediate",
  },
  {
    title: "ReTool",
    description: "Learn everything you need to know about Ads with this course",
    price: 100,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "SEO",
    description: "Learn everything you need to know about Ads with this course",
    price: 100,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "Linux Server Management",
    description: "Learn everything you need to know about Ads with this course",
    price: 100,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "ClickUp APIs",
    description: "Learn everything you need to know about Ads with this course",
    price: 100,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "Supabase",
    description: "Learn everything you need to know about Ads with this course",
    price: 100,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "Airtable",
    description: "Learn everything you need to know about Ads with this course",
    price: 100,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "Email Marketing",
    description: "Learn everything you need to know about Ads with this course",
    price: 100,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "Docker",
    description: "Learn everything you need to know about Ads with this course",
    price: 100,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "FileSystems and Storage for Node.js",
    description: "Learn everything you need to know about Ads with this course",
    price: 0,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "ChatGPT",
    description: "Learn everything you need to know about Ads with this course",
    price: 0,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "Dall3",
    description: "Learn everything you need to know about Ads with this course",
    price: 0,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "Sora",
    description: "Learn everything you need to know about Ads with this course",
    price: 0,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "Unfiltered AI",
    description: "Learn everything you need to know about Ads with this course",
    price: 0,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "Chatbot with ChatGPT",
    description: "Learn everything you need to know about Ads with this course",
    price: 0,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
  {
    title: "Facebook Ads",
    description: "Learn everything you need to know about Ads with this course",
    price: 0,
    slug: "facebook-ads-for-developers",
    difficulty: "Begginer",
  },
];
